### ISSUE TITLE
[Suggestion] Support usbfluxd

### ISSUE THREAD

**Issue by turannul** [NyaMisty/AltServer-Linux#24]
If possible this possible It would be amazing.
Title clear enough?

**Comment by turannul** [comment]
label:"help wanted"

**Comment by NyaMisty** [comment]
Not that useful?

**Comment by turannul** [comment]
> Not that useful?

how not useful emulating USB connection over network?

**Comment by NyaMisty** [comment]
Why? Because usbfluxd are now only used by Corellium-like service.

**Comment by turannul** [comment]
> Why? Because usbfluxd are now only used by Corellium-like service.

We can modify to make possible connect with usb without physical cable.
My main reason aws virtual machine use as AltDeamon

**Comment by powenn** [comment]
> Why? Because usbfluxd are now only used by Corellium-like service.

I have question about the latest AltServer-Linux release 
Will u compile x64 support version?
So we don't need to use it with qemu ,some desktop user might need,but it is not necessary to build new one ,the previous release works

**Comment by jgottula** [comment]
This is probably quite a bit less "automagic" and user-friendly... but I figure it's worth pointing out that **usbip** is also out there as a generic way to "tunnel" communication with any type of USB device on a remote system over the network so that it appears and operates essentially as if it's a USB device connected directly to the local system.

I've used it before for some other projects, and it generally works. (I haven't specifically used it for usbmuxd / Apple Mobile Device use cases, but I don't think anything would break.)

Again, it's not a tremendously user-friendly solution, so probably not something you'd want to package in as an actual feature. But it's another option available for anyone out there who wants to tinker around with this sort of thing.

**Comment by jgottula** [comment]
Actually perhaps usbip would have problems... since it forwards the entire USB device rather than just the higher level protocol stuff. So maybe the device would, like, trust-pair to the usbip client system versus the usbfluxd server system and that'd be different and break stuff. 🤔

Never attempted it, so I'm not sure.

**Comment by Spidy123222** [comment]
Difference is that on libimobiledevice on pc using this module it interfaces like a hub so like usb over ip which doesn't work on iOS directly. I've tried it only works by connecting to another device that has a usbmuxd instance. So it's kind of like a usb over ip thing itself to 2 different computers. 

Description:

Usbfluxd Redirects the standard usbmuxd socket to allow connections to local and remote usbmuxd instances so remote devices appear connected locally.

**Comment by NyaMisty** [comment]
I recently have a chance to try out the usbfluxd, and it seems that usbfluxd is capable to detect the iOS devices in the same network (even over VPN).
So AltServer-Linux's network version will be totally abandoned. 
For install IPA over WiFi, you can run the usbfluxd before AltServer-Linux.

**Comment by NyaMisty** [comment]
For usbfluxd, its mDNS is only used for finding other usbfluxd, so sadly not useful.
For usbmuxd2, it's very unstable, so not useful
Have to wait for usbmuxd to support network device.
