### ISSUE TITLE
Apple tokens calculation

### ISSUE THREAD

**Issue by foiki** [NyaMisty/AltServer-Linux#3]
https://github.com/NyaMisty/AltServer-Linux/blob/a9f97b7cc210f9ad893ce18ac8bde233910731ac/src/AnisetteDataManager.cpp#L52

Do you have a solution for calculating X-Apple-I-MD-M and X-Apple-I-MD, instead of using constant values?

**Comment by NyaMisty** [comment]
Learn more before post some wrong statements.

**Comment by DebianArch64** [comment]
> https://github.com/NyaMisty/AltServer-Linux/blob/a9f97b7cc210f9ad893ce18ac8bde233910731ac/src/AnisetteDataManager.cpp#L52
> 
> Do you have a solution for calculating X-Apple-I-MD-M and X-Apple-I-MD, instead of using constant values?

I happened to walk into this thread.
AltServer Linux uses an anisette server provided by iOSGods - the reason for an anisette server is the opposite although X-Apple-I-MD is a constant, X-Apple-I-MD-M is not (needs to be changed every 90 seconds or so).
Pretty much all anisette headers are actually pretty easy to reproduce especially since they are mostly user-specified like X-Apple-I-MD-LU which is just a SHA256 of the username of the device.

X-Apple-I-MD and X-Apple-I-MD-M aren't exactly "calculated" you have to contact apple's API to get spim and from that cpim then you get keys that nobody I know knows how to use, so the best route, for now, is either hooking into iTunes or using an anisette server

**Comment by NyaMisty** [comment]
True, but now you can spin up a anisette server using my alt-anisette-server to avoid -36607 error
