### ISSUE TITLE
Where/how to get AltStore?

### ISSUE THREAD

**Issue by ghost** [NyaMisty/AltServer-Linux#72]
I'm using _altserver-linux-gui_, which asks that all questions be posted here, so where to get the AltStore.ipa file? It says to add it to the resources folder before running build.sh, but I can't find it anywhere online. Can anyone help?

**Comment by sandstripes** [comment]
You can find the default AltStore apps at https://github.com/rileytestut/AltStore/blob/master/AltStore/Resources/apps-alpha.json (including AltStore itself), so hopefully that helps.

**Comment by brkzlr** [comment]
Use this link instead of the one from above: https://github.com/rileytestut/AltStore/blob/master/AltStore/Resources/apps.json

The issue with the alpha link is that it contains the old version of AltStore (1.4.2 to be more specific) and rest of the apps.
You cannot install .ipa's through that AltStore because it will complain about code signing version being out of date.
The downside of AltStore 1.5 from this new link is that you won't be able to add custom untrusted sources because it's a Patreon exclusive feature, but it wouldn't matter since you cannot install .ipa manually or through untrusted sources in 1.4.2 anyway

**Comment by ghost** [comment]
Thanks for the help!

**Comment by Legomountain14** [comment]
For anyone looking, check here: https://cdn.altstore.io/file/altstore/apps.json
